--- Makefile	2019-03-27 00:18:00.000000000 -0500
+++ Makefile.patched	2019-04-03 16:32:46.000000000 -0500
@@ -13,6 +13,8 @@
 			   hyperv.o page_track.o debugfs.o
 
 kvm-intel-y		+= vmx/vmx.o vmx/vmenter.o vmx/pmu_intel.o vmx/vmcs12.o vmx/evmcs.o vmx/nested.o
+kvm-intel-$(CONFIG_KVM_VMX_PT) += vmx_pt.o
+
 kvm-amd-y		+= svm.o pmu_amd.o
 
 obj-$(CONFIG_KVM)	+= kvm.o
